
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzvfxcbgegfswyclhzuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56dmZ4Y2JnZWdmc3d5Y2xoenV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NjAxNzUsImV4cCI6MjA2MzEzNjE3NX0.emPBnItIxFOb3c3K8FybHJPVr4peJFGoT32u6-1KylI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Helper function to get a URL for an image in the product_images bucket
export const getImageUrl = (path: string) => {
  if (!path) return '/placeholder.svg';
  
  if (path.startsWith('http') || path.startsWith('/')) {
    return path;
  }
  
  return `${SUPABASE_URL}/storage/v1/object/public/product_images/${path}`;
};
